# Generated by Django 2.2.2 on 2020-05-11 08:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999999)], verbose_name='価格')),
                ('memo', models.TextField(verbose_name='商品説明')),
                ('status', models.CharField(choices=[('1', '新品未使用'), ('2', '未使用に近い'), ('3', '目立った傷や汚れなし'), ('4', '全体的に状態が悪い')], max_length=100, verbose_name='商品状態')),
                ('shipping_burden', models.CharField(choices=[('1', '送料込み（出品者負担）'), ('2', '着払い（購入者負担）'), ('3', '未定'), ('4', '7日以内'), ('5', '未定')], max_length=100, verbose_name='発送料の負担')),
                ('shipping_area', models.CharField(choices=[('1', '北海道'), ('2', '東京')], max_length=10, verbose_name='発送地域')),
                ('shipping_days', models.CharField(choices=[('1', '即日'), ('2', '２〜３日以内'), ('3', '5日以内'), ('4', '7日以内'), ('5', '未定')], max_length=100, verbose_name='発送までの日数')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='', verbose_name='出品画像1')),
                ('photo2', models.ImageField(upload_to='', verbose_name='出品画像2')),
                ('photo3', models.ImageField(upload_to='', verbose_name='出品画像3')),
                ('photo4', models.ImageField(upload_to='', verbose_name='出品画像4')),
                ('photo5', models.ImageField(upload_to='', verbose_name='出品画像5')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Item')),
            ],
        ),
    ]
