# Generated by Django 2.2.2 on 2020-04-19 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200419_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
