# Generated by Django 2.2.2 on 2020-04-19 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200419_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='shipping_area',
            field=models.CharField(choices=[('1', '即日'), ('2', '２〜３日以内'), ('3', '5日以内'), ('4', '7日以内'), ('5', '未定')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='shipping_burden',
            field=models.CharField(choices=[('1', '送料込み（出品者負担）'), ('2', '着払い（購入者負担）'), ('3', '未定'), ('4', '7日以内'), ('5', '未定')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='shipping_days',
            field=models.CharField(choices=[('1', '即日'), ('2', '２〜３日以内'), ('3', '5日以内'), ('4', '7日以内'), ('5', '未定')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
