# Generated by Django 2.2.2 on 2020-04-19 18:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200419_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='ability',
            field=models.TextField(verbose_name='商品説明'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999999)], verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='shipping_area',
            field=models.CharField(max_length=10, verbose_name='発送地域'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='shipping_burden',
            field=models.CharField(choices=[('1', '送料込み（出品者負担）'), ('2', '着払い（購入者負担）'), ('3', '未定'), ('4', '7日以内'), ('5', '未定')], max_length=100, verbose_name='発送料の負担'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='shipping_days',
            field=models.CharField(choices=[('1', '即日'), ('2', '２〜３日以内'), ('3', '5日以内'), ('4', '7日以内'), ('5', '未定')], max_length=100, verbose_name='発送までの日数'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='status',
            field=models.CharField(choices=[('1', '新品未使用'), ('2', '未使用に近い'), ('3', '目立った傷や汚れなし'), ('4', '全体的に状態が悪い')], max_length=100, verbose_name='商品状態'),
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='', verbose_name='出品画像')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ItemModel')),
            ],
        ),
    ]
